import {mapPalette as p,type ModularDestination} from '@/lib/modular-map';
import {projectGround} from '@/lib/map-projection';
import {communityLots} from '@/lib/community-study';
import CivicRenderedProp from './civic-rendered-prop';
const pt=(x:number,y:number,z=0)=>`${(x-y)*.5196152423},${(x+y)*.3-z}`;
function Box({x=0,y=0,z=0,w,d,h,color}:{x?:number;y?:number;z?:number;w:number;d:number;h:number;color:string}){const a=[x-w/2,y-d/2],b=[x+w/2,y-d/2],c=[x+w/2,y+d/2],e=[x-w/2,y+d/2];const at=(v:number[],height:number)=>pt(v[0],v[1],height);return <g stroke={p.ink} strokeWidth="1.6" strokeLinejoin="round"><polygon points={`${at(e,z)} ${at(c,z)} ${at(c,z+h)} ${at(e,z+h)}`} fill={color}/><polygon points={`${at(c,z)} ${at(b,z)} ${at(b,z+h)} ${at(c,z+h)}`} fill={color}/><polygon points={`${at(c,z)} ${at(b,z)} ${at(b,z+h)} ${at(c,z+h)}`} fill={p.ink} opacity=".12"/><polygon points={`${at(a,z+h)} ${at(b,z+h)} ${at(c,z+h)} ${at(e,z+h)}`} fill={p.cream}/></g>;}
function Local({x=0,y=0,children}:{x?:number;y?:number;children:React.ReactNode}){return <g transform={`translate(${(x-y)*.5196152423} ${(x+y)*.3})`}>{children}</g>;}
function Front({x,y,w,h,z=0,color}:{x:number;y:number;w:number;h:number;z?:number;color:string}){return <polygon points={`${pt(x,y,z)} ${pt(x+w,y,z)} ${pt(x+w,y,z+h)} ${pt(x,y,z+h)}`} fill={color} stroke={p.ink} strokeWidth="1.4"/>;}
function Building({kind}:{kind:string}){if(kind==='departamento-xerifins')return <CivicRenderedProp kind="sheriffBuilding" x={-20} y={-70}/>;if(kind==='inglish-pub')return <CivicRenderedProp kind="inglishPub" x={-20} y={-70}/>;if(kind==='estudio-criativins')return <CivicRenderedProp kind="creativeStudio" x={-20} y={-70}/>;const studio=kind==='estudio-criativins',sheriff=kind==='departamento-xerifins';return <Local x={-20} y={-70}>
 <Box w={225} d={140} h={100} color={studio?p.yellow:sheriff?p.blue:p.coral}/>
 <Front x={-100} y={70} w={55} h={58} z={14} color="#A3D3E2"/><Front x={-28} y={70} w={45} h={78} color={p.blue}/><Front x={40} y={70} w={60} h={58} z={14} color="#A3D3E2"/>
 <Front x={-106} y={71} w={212} h={16} z={82} color={sheriff?p.yellow:studio?p.pink:p.blue}/>
 {!sheriff&&<g transform="translate(0 -82)"><Box y={86} w={240} d={38} h={7} color={studio?p.pink:p.yellow}/></g>}
 <g transform="translate(0 -120)" stroke={p.ink} strokeWidth="2" fill={p.yellow}>
 {sheriff?<path d="M0-17L5-7L17-7L10 2L13 14L0 8L-13 14L-10 2L-17-7L-5-7Z"/>:studio?<><ellipse rx="19" ry="13" fill={p.cream}/><circle cx="-9" cy="-4" r="3" fill={p.coral}/><circle cx="2" cy="-6" r="3" fill={p.blue}/><path d="M8 8L21-14"/></>:<><path d="M-11-10H8V12H-11Z" fill={p.cream}/><path d="M8-6Q22-7 19 6Q18 10 8 8" fill="none"/><path d="M-11-10H8V-5H-11Z"/></>}
 </g></Local>;}
function Easel({x,y,color}:{x:number;y:number;color:string}){return <Local x={x} y={y}><title>Cavalete de exposição</title><path d={`M${pt(-18,0)}L${pt(0,0,60)}L${pt(18,0)}M${pt(0,12)}L${pt(0,0,50)}`} stroke={p.ink} strokeWidth="2.5" fill="none"/><Front x={-16} y={0} w={32} h={30} z={20} color={p.cream}/><Front x={-11} y={.5} w={22} h={18} z={25} color={color}/></Local>;}
function Furnishings({kind}:{kind:string}){
 if(kind==='inglish-pub')return <><CivicRenderedProp kind="tavernRoundTable" x={-105} y={115}/><CivicRenderedProp kind="tavernRoundTable" x={20} y={135}/><CivicRenderedProp kind="pubSpeaker" x={-130} y={30}/><CivicRenderedProp kind="pubStage" x={110} y={45}/><CivicRenderedProp kind="pubMicrophone" x={110} y={45}/></>;
 if(kind==='estudio-criativins')return <><CivicRenderedProp kind="creativeEasel" x={-115} y={105}/><CivicRenderedProp kind="creativeEasel" x={0} y={135}/><CivicRenderedProp kind="creativeSculpture" x={100} y={85}/><CivicRenderedProp kind="creativeBench" x={-120} y={25}/></>;
 return <><g><title>Guarita de atendimento renderizada</title><CivicRenderedProp kind="sheriffBooth" x={100} y={-5}/></g><Local x={100} y={105}><title>Veículo de patrulha na vaga reservada</title><polygon points={`${pt(-40,-30)} ${pt(40,-30)} ${pt(40,30)} ${pt(-40,30)}`} fill="none" stroke={p.blue} strokeWidth="2" strokeDasharray="5 4"/><CivicRenderedProp kind="sheriffCar"/></Local></>;
}
export function CommunityGround(){return <g data-layer="community-study-ground">{communityLots.map(l=><g key={l.id} transform={`translate(${l.x} ${l.y})`}><rect x={-l.size/2+6} y={-l.size/2+6} width={l.size} height={l.size} rx="24" fill="#B6A487"/><rect x={-l.size/2} y={-l.size/2} width={l.size} height={l.size} rx="24" fill={p.cream} stroke={p.ink} strokeWidth="3"/><rect x={-l.size/2+12} y={-l.size/2+12} width={l.size-24} height={l.size-24} rx="16" fill="none" stroke={l.color} strokeWidth="6"/></g>)}</g>;}
export default function CommunityStudy({destination:d,selected,onSelect}:{destination:ModularDestination;selected:string|null;onSelect:(id:string,keyboard?:boolean)=>void}){const lot=communityLots.find(l=>l.id===d.id)!;const at=projectGround(lot.x,lot.y);return <g id={`destination-${d.id}`} transform={`translate(${at.x} ${at.y})`} className={`modular-destination ${selected===d.id?'is-selected':''}`} role="group" aria-label={d.name}><title>{`${d.name} — espaço renderizado`}</title><Building kind={d.id}/><Furnishings kind={d.id}/></g>;}
