import type { Target } from './game-data';

export const mapCharacters: (Target & { file: string; elevation?: number; isSheriff?: boolean })[] = [
  { id: 'diego-ungari', name: 'Diego Ungari', article: 'o', category: 'people', x: 1600, y: -730, width: 48, height: 39, file: '/images/characters/diego-ungari-v02.png', clue: 'Diego mora na casinha da clareira e está sentado em um tronco, de moletom rosa, botas verdes e caneca na mão, perto de seu cachorro.' },
  { id: 'elton-pavesi', name: 'Elton Pavesi', article: 'o', category: 'people', x: 2795, y: 375, width: 30, height: 45, file: '/images/characters/elton-pavesi-v02.png', clue: 'Elton está sentado em um banquinho na região da taverna dos joguINs, segurando um aviãozinho em uma mão e um pedaço de queijo na outra.' },
  { id: 'davi-cabeca', name: 'Davi Cabeça', article: 'o', category: 'people', x: -95, y: -25, elevation: 14, width: 18, height: 20, file: '/images/characters/davi-cabeca-v01.png', clue: 'Davi é uma cabeça flutuante de cabelos cacheados e barba, em meio à Parada do Orgulho LGBT no cantIN coloridIN.' },
  { id: 'loisi-vieira', isSheriff: true, name: 'Loisi Vieira', article: 'a', category: 'people', x: 2690, y: 245, width: 49, height: 45, file: '/images/characters/loisi-vieira-v01.png', clue: 'Loisi está na área da taverna dos joguINs, empurrando um carrinho de supermercado e usando uma estrela de xerife no peito.' },
  { id: 'henrique-hardman', name: 'Henrique Hardman', article: 'o', category: 'people', x: 260, y: 55, elevation: 61, width: 34, height: 38, file: '/images/characters/henrique-hardman-v02.png', clue: 'Henrique está agachado no teto do vagão feminino, com um pé de cabra junto ao alçapão fechado com cadeado.' },
  { id: 'patrick-canuto', isSheriff: true, name: 'Patrick Canuto', article: 'o', category: 'people', x: 2828, y: 130, width: 30, height: 45, file: '/images/characters/patrick-canuto-v01.png', clue: 'Patrick é o taverneiro de roupas medievais, óculos, estrela de xerife e controle de videogame, diante da taverna junto à floresta.' },
  { id: 'paula-lotti', name: 'Paula Lotti', article: 'a', category: 'people', x: 2080, y: 2050, width: 30, height: 45, file: '/images/characters/paula-lotti-v02.png', clue: 'Paula está na praia, cavando a areia com uma pá. Procure os cabelos cacheados e a camisa listrada verde e branca.' },
  { id: 'gabriel-martins', isSheriff: true, name: 'Gabriel Martins', article: 'o', category: 'people', x: 415, y: 570, width: 30, height: 45, file: '/images/characters/gabriel-martins-v02.png', clue: 'Gabriel está com sua pipoca no canto direito do terreno do cinema.' },
  { id: 'nathan-machado', name: 'Nathan Machado', article: 'o', category: 'people', x: 1400, y: 1970, width: 30, height: 45, file: '/images/characters/nathan-machado-v01.png', clue: 'Nathan está fazendo exercício com halteres no gINásio dos marombINs. Procure o machado na camiseta dele.' },
  { id: 'kauana-moreira', name: 'Kauana Moreira', article: 'a', category: 'people', x: 2410, y: 2180, width: 30, height: 45, file: '/images/characters/kauana-moreira-v01.png', clue: 'Kauana está entre os animais da savana, de boné e óculos escuros, perto de uma ovelhinha branca com asas e auréola.' },
];
