import type { Target } from './game-data';

export const mapCharacters: (Target & { file: string; elevation?: number })[] = [
  { id: 'loisi-vieira', name: 'Loisi Vieira', article: 'a', category: 'people', x: 2690, y: 245, width: 49, height: 45, file: '/images/characters/loisi-vieira-v01.png', clue: 'Loisi está na área da taverna dos joguINs, empurrando um carrinho de supermercado e usando uma estrela de xerife no peito.' },
  { id: 'henrique-hardman', name: 'Henrique Hardman', article: 'o', category: 'people', x: 260, y: 55, elevation: 61, width: 34, height: 38, file: '/images/characters/henrique-hardman-v01.png', clue: 'Henrique está agachado no teto do vagão feminino, com um pé de cabra junto ao alçapão fechado com cadeado.' },
  { id: 'patrick-canuto', name: 'Patrick Canuto', article: 'o', category: 'people', x: 2828, y: 130, width: 30, height: 45, file: '/images/characters/patrick-canuto-v01.png', clue: 'Patrick é o taverneiro de roupas medievais, óculos, estrela de xerife e controle de videogame, diante da taverna junto à floresta.' },
  { id: 'paula-lotti', name: 'Paula Lotti', article: 'a', category: 'people', x: 2080, y: 2050, width: 30, height: 45, file: '/images/characters/paula-lotti-v02.png', clue: 'Paula está na praia, cavando a areia com uma pá. Procure os cabelos cacheados e a camisa listrada verde e branca.' },
  { id: 'gabriel-martins', name: 'Gabriel Martins', article: 'o', category: 'people', x: 415, y: 570, width: 30, height: 45, file: '/images/characters/gabriel-martins-v01.png', clue: 'Gabriel está com sua pipoca no canto direito do terreno do cinema.' },
  { id: 'nathan-machado', name: 'Nathan Machado', article: 'o', category: 'people', x: 1400, y: 1970, width: 30, height: 45, file: '/images/characters/nathan-machado-v01.png', clue: 'Nathan está fazendo exercício com halteres no gINásio dos marombINs. Procure o machado na camiseta dele.' },
  { id: 'kauana-moreira', name: 'Kauana Moreira', article: 'a', category: 'people', x: 2410, y: 2180, width: 30, height: 45, file: '/images/characters/kauana-moreira-v01.png', clue: 'Kauana está entre os animais da savana, de boné e óculos escuros, perto de uma ovelhinha branca com asas e auréola.' },
];
